---

- name: Generating RSA key
  user:
    name: "{{ item }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: ".ssh/id_rsa"
    ssh_key_type: rsa
    ssh_key_comment: "ansible-generated {{ item }}@{{ inventory_hostname }}"
  with_items: "{{ sshkeygen }}"
  tags:
    - ssh-keygen

