---

- name: install packages
  apt:
    update_cache: yes
    pkg:
      - zsh
    state: present


- name: zsh configuration files
  copy:
    src: "../files/{{ item }}"
    dest: "/etc/zsh"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - "zlogin"
    - "zlogout"
    - "zshenv"
    - "zshrc"
