---
# tasks file for common

- name: Update system
  apt: update_cache=yes
  tags: base-install


- name: Upgrading system
  apt: upgrade=dist
  tags: base-install


- name: Installing common packages
  apt: name='{{ item }}' state=present
  with_items:
    - python-setuptools
    - python3-setuptools
    - sudo
  tags: base-install

- name: Installing extra packages
  apt: name='{{ item }}' state=present
  with_items:
    - "{{ extra_packages }}"
  tags: extra-packages

- name: Installing extra files
  ignore_errors: yes
  copy:
    src: "../files/{{ item.value.src }}"
    dest: "{{ item.value.dest }}"
    owner: "{{ item.value.owner }}"
    group: "{{ item.value.group }}"
    mode: "{{ item.value.mode }}"
    backup: "{{ item.value.backup | default('no') }}"
  with_dict: "{{ extra_files }}"
  tags: extra-files

- name: Set ip forwarding on in /proc and in the sysctl file and reload if necessary
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  tags: ip-forwarding
